version: '3.8'
services:
  server:
    container_name: next-equities-server
    build:
      context: next-equities-server
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/next-equities
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-username}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-password}
    healthcheck:
      test: "exit 0"
    depends_on:
      - postgres
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-username}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      PGDATA: /data/postgres
      POSTGRES_DB: ${DB_PG:-next-equities}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
